ingress:
  hosts:
    - staging.runbooks.starkandwayne.com
    - staging.runbooks.k8s.lke.starkandwayne.com
  tls:
    enabled: true
    certIssuer: "lab-ca-issuer"

app:
  org: starkandwayne
  repo: runbooks

  setup_script: |
    #!/bin/sh
    mv /tmp/website/web/* /var/www/
    
